# Generated by Django 3.0.6 on 2020-06-18 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_author_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-user'], 'verbose_name': 'комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
